# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A web developer's garage
email: me@mydomain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a web developer website.
baseurl: "/dp" # the subpath of your site, e.g. /blog
url: "http://fixsitenow.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalinks: /:categories/:title

#links:

# Build settings
markdown: redcarpet
